### ISSUE TITLE
jupyter not oppening at all

### ISSUE THREAD

**Issue by humandotlearning** [snarkai/snark-doc#3]
after i started my pod i tried to run jupyter but it is not running. i'm using ubuntu 18.04.

**Comment by davidbuniat** [comment]
Could you please provide the command line you executed and the output?

**Comment by humandotlearning** [comment]
nevermind i understood how to use it. i was trying to open jupyter after starting the pod. 

thank you

**Comment by davidbuniat** [comment]
Cool! You could also use `snark attach pod_id -L 8888:localhost:8888` after you execute the pod and run jupyter from inside.
