### ISSUE TITLE
how can you get back to your pod after stopping it?

### ISSUE THREAD

**Issue by humandotlearning** [snarkai/snark-doc#4]

**Comment by humandotlearning** [comment]
i am not able to resume my work after stopping the pod

**Comment by davidbuniat** [comment]
`snark ls` get pod_id then `snark attach pod_id`

**Comment by humandotlearning** [comment]
no wouldn't i be charged if i keep my snark pod attached?

**Comment by humandotlearning** [comment]
i want to stop it for the day and resume working on it the next day. how do i do that?

**Comment by davidbuniat** [comment]
Please run `snark stop pod_id` and then tomorrow start a new pod. Your files would persist, but not environment changes.

**Comment by humandotlearning** [comment]
so you are telling me that the files that i upload would remain in the pod but the packages that i install won't work after i restart my pod? do i understand you correct?

**Comment by humandotlearning** [comment]
it would be very tedious to install the environment every single time you restart the pod.

**Comment by davidbuniat** [comment]
We are actively working on that direction to make it very easy for users to do that as well. However for now you can prebuilt your environment including your packages inside a docker and launch it with.

`start -t custom --docker_image username/image:tag`

Another hack: if you install your packages with `pip install ... --user` and store locally under your home directory, your packages should stay next time you start a pod.

**Comment by humandotlearning** [comment]
thank you for that i'll try the same.
